# Uncomment these two line to add support for encoders to your firmware
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment the following line to enable the Kyria OLED Display
# CONFIG_ZMK_DISPLAY=y

# Uncomment the following lines to enable RGB underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# Enable USB logging
CONFIG_ZMK_USB_LOGGING=y

# Optional: Increase the log level for more detail (default is Info)
# CONFIG_LOG_MAX_LEVEL=4

# Useful if you want to see boot logs before the serial port connects
CONFIG_LOG_PROCESS_THREAD_START_UP_DELAY_MS=8000
